[package]
name = "mixxx_data"
version = "0.1.0"
authors = ["Felix hennig"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.24"
prost = "0.6"
simplemad = "0.9"
